In [3]:
import pandas as pd

In [88]:
df = pd.read_csv('diabetes.csv')


# df[['pregnancies', 'glucose', 'bmi']].min()
df[['pregnancies', 'glucose', 'bmi']].agg(['min', 'max', 'mean', 'median', 'std'])

        pregnancies     glucose        bmi
min        0.000000   14.000000   9.700000
max       11.000000  199.000000  54.300000
mean       3.598000  118.700000  31.442400
median     3.000000  119.000000  31.650000
std        2.132826   31.803104   7.217014

In [27]:
df[['bloodpressure', 'glucose']]

     bloodpressure  glucose
0               79      147
1               71      168
2               70      112
3               75       76
4               79      120
..             ...      ...
995             85       50
996             78      122
997             65       74
998             59      141
999             58       74

[1000 rows x 2 columns]

In [44]:
filter_df = df[(df['bloodpressure'] > 70) & (df['glucose'] > 100)]
filter_df.agg(['mean', 'min', 'max'])

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefu,outcome
mean,4.009317,134.875776,79.686335,22.571429,149.310559,32.728571,0.717932,0.509317
min,0.000000,101.000000,71.000000,0.000000,6.000000,9.700000,0.078000,0.000000
max,10.000000,199.000000,105.000000,77.000000,846.000000,54.300000,2.016000,1.000000

In [92]:
df['bloodpressure'].unique().shape[0]
df.shape

df.groupby('outcome', as_index=False)['bmi'].mean()

   outcome        bmi
0        0  29.710134
1        1  34.975380

In [93]:
df.groupby('outcome', as_index=False).agg(
    avg_glucose = ('glucose', 'mean'),
    max_bmi = ('bmi', 'max')
)

   outcome  avg_glucose  max_bmi
0        0   110.007452     49.1
1        1   136.428571     54.3